// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship['fields'][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship['id']]: ContentRelationshipFieldWithData<
      TSubRelationship['customtypes'],
      TLang
    >;
  } & { // Group
    [TGroup in Extract<
      TRelationship['fields'][number],
      prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<infer TGroupData>
      ? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
      : never;
  } & { // Other fields
    [TFieldKey in Extract<TRelationship['fields'][number], string>]: TFieldKey extends keyof TData
      ? TData[TFieldKey]
      : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<TCustomType[number], string>['id']]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>['id']];

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
interface GDocumentData {}

/**
 * g document from Prismic
 *
 * - **API ID**: `g`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<GDocumentData>,
  'g',
  Lang
>;

type HomeDocumentDataSlicesSlice = FeaturedBadgeSlice;

/**
 * Content for Home  documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home *
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home *
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home *
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home *
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home  document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<HomeDocumentData>,
  'home',
  Lang
>;

export type AllDocumentTypes = GDocument | HomeDocument;

/**
 * Primary content in *FeaturedBadge → Default → Primary*
 */
export interface FeaturedBadgeSliceDefaultPrimary {
  /**
   * Badge Graphic field in *FeaturedBadge → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_badge.default.primary.badge_graphic
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  badge_graphic: prismic.ImageField<never>;

  /**
   * Primary Text field in *FeaturedBadge → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_badge.default.primary.primary_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  primary_text: prismic.RichTextField;

  /**
   * Secondary Text field in *FeaturedBadge → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_badge.default.primary.secondary_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  secondary_text: prismic.RichTextField;
}

/**
 * Default variation for FeaturedBadge Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with an image (for the badge graphic) and two main structured text fields (for upper and lower lines of bold text).
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedBadgeSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FeaturedBadgeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedBadge*
 */
type FeaturedBadgeSliceVariation = FeaturedBadgeSliceDefault;

/**
 * FeaturedBadge Shared Slice
 *
 * - **API ID**: `featured_badge`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedBadgeSlice = prismic.SharedSlice<'featured_badge', FeaturedBadgeSliceVariation>;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      GDocument,
      GDocumentData,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      FeaturedBadgeSlice,
      FeaturedBadgeSliceDefaultPrimary,
      FeaturedBadgeSliceVariation,
      FeaturedBadgeSliceDefault,
    };
  }
}

