#!/usr/bin/env node
/**
 * 3000 Studios — Intent Engine
 * Canonical source of truth for natural language → code changes
 * This file MUST be deterministic, defensive, and loud on failure
 */

import fs from 'fs';
import path from 'path';
import process from 'process';
import { execSync } from 'child_process';

const INTENT = fs.readFileSync(0, 'utf8').trim();
if (!INTENT) {
  console.error('❌ No intent provided');
  process.exit(1);
}

console.log('▶ INTENT RECEIVED:');
console.log(INTENT);
console.log('────────────────────────');

const ROOT = process.cwd();

/* ---------------------------
   Utility helpers
----------------------------*/

function listFiles(dir, exts, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.')) continue;
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) listFiles(p, exts, out);
    else if (exts.some((e) => p.endsWith(e))) out.push(p);
  }
  return out;
}

function read(file) {
  return fs.readFileSync(file, 'utf8');
}

function write(file, content) {
  fs.writeFileSync(file, content);
}

function changed(original, next) {
  return original !== next;
}

function fail(msg) {
  console.error('❌ INTENT FAILED:', msg);
  process.exit(1);
}

/* ---------------------------
   Intent classification
----------------------------*/

const intent = INTENT.toLowerCase();

const actions = {
  remove: /remove|delete|strip|kill|get rid of/,
  add: /add|insert|create|new/,
  modify: /change|update|make|set/,
};

const targets = {
  style: /color|font|size|style|css|theme/,
  page: /page|route|screen|view/,
  media: /image|picture|photo|gallery/,
  animation: /animate|animation|loop|spin|fade|bounce|flip/,
};

function match(map) {
  return Object.entries(map).find(([, rx]) => rx.test(intent))?.[0];
}

const ACTION = match(actions);
const TARGET = match(targets);

if (!ACTION || !TARGET) {
  fail('Unable to infer actionable intent');
}

console.log(`✔ ACTION: ${ACTION}`);
console.log(`✔ TARGET: ${TARGET}`);

/* ---------------------------
   Apply logic
----------------------------*/

let filesTouched = 0;

/* === STYLE / CSS === */
if (TARGET === 'style') {
  const cssFiles = listFiles(ROOT, ['.css', '.scss', '.tsx', '.jsx']);

  cssFiles.forEach((file) => {
    let src = read(file);
    let next = src;

    if (/pink/.test(intent)) {
      next = next.replace(/pink/gi, 'transparent');
    }

    const sizeMatch = intent.match(/(\d+)\s*(px|rem|em)?/);
    if (sizeMatch && /font/.test(intent)) {
      const size = sizeMatch[1] + (sizeMatch[2] || 'px');
      next = next.replace(/font-size:\s*[^;]+;/gi, `font-size: ${size};`);
    }

    if (changed(src, next)) {
      write(file, next);
      filesTouched++;
    }
  });
}

/* === ADD PAGE === */
if (TARGET === 'page' && ACTION === 'add') {
  const slug = intent.match(/page\s+called\s+([a-z0-9-]+)/)?.[1] ?? 'new-page';

  const pageDir = path.join(ROOT, 'app', slug);
  if (fs.existsSync(pageDir)) {
    fail(`Page "${slug}" already exists`);
  }

  fs.mkdirSync(pageDir, { recursive: true });

  write(
    path.join(pageDir, 'page.tsx'),
    `
export default function Page() {
  return (
    <main style={{ padding: "4rem" }}>
      <h1>${slug.replace('-', ' ')}</h1>
      <p>Generated by 3000 Agent</p>
    </main>
  );
}
`.trim()
  );

  filesTouched++;
}

/* === MEDIA INSERT === */
if (TARGET === 'media' && ACTION === 'add') {
  const components = listFiles(ROOT, ['.tsx', '.jsx']);

  components.forEach((file) => {
    let src = read(file);
    if (!/img|Image/.test(src)) {
      const injected = src.replace(
        /return\s*\(/,
        `return (\n<img src="https://source.unsplash.com/random/800x600" alt="auto" />\n`
      );
      if (changed(src, injected)) {
        write(file, injected);
        filesTouched++;
      }
    }
  });
}

/* === ANIMATION === */
if (TARGET === 'animation') {
  const components = listFiles(ROOT, ['.tsx', '.jsx']);

  components.forEach((file) => {
    let src = read(file);
    let next = src;

    if (/header|h1/.test(src)) {
      next = src.replace(/<h1([^>]*)>/, `<h1$1 style={{ animation: "spin 2s linear infinite" }}>`);
    }

    if (changed(src, next)) {
      write(file, next);
      filesTouched++;
    }
  });

  const globals = path.join(ROOT, 'app', 'globals.css');
  if (fs.existsSync(globals)) {
    let css = read(globals);
    if (!/spin/.test(css)) {
      css += `
@keyframes spin {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}
`;
      write(globals, css);
      filesTouched++;
    }
  }
}

/* ---------------------------
   Final validation
----------------------------*/

if (filesTouched === 0) {
  fail('Intent produced no deterministic changes');
}

console.log(`✅ Files modified: ${filesTouched}`);
console.log('✔ Intent applied successfully');

/* Safety: ensure repo is dirty */
try {
  const status = execSync('git status --porcelain').toString().trim();
  if (!status) fail('No git changes detected after intent application');
} catch {
  fail('Git status failed');
}
